services:
  ingest:
    container_name: ingest-data
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python ingest.py

  llm-chatbot-app:
    container_name: llm-chatbot-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - ingest
    command: python app.py
